### ISSUE TITLE
config

### ISSUE THREAD

**Issue by cvockrodt** [ianoshorty/RPVR#1]
I'm trying to install, but I'm getting Error: Unknown asset: config/public_config.json when i run meteor.

I found the example json in RPVR/private/config/ 

Where does the public_config.json file go? Are there any other steps to get everything installed?

**Comment by ianoshorty** [comment]
Hi. 
This repo was never finished andI haven't looked at it in a long time. Its likely that it is way out of date as compared to current Meteor etc. I would recommend choosing another package to base from. 

My gut feeling is that there is was either a RPVR/config/public_config.json or RPVR/private/config/public_config.json file but in truth I cant even remember.

Sorry about that!
